### ISSUE TITLE
AEM Deployment script voor Mac

### ISSUE THREAD

**Issue by jasper1986** [opendns/Deploy-Scripts#3]
Hi,

We are using the DeployUmbrellaRoamingClient.cpt for AEM to deploy to Windows and this works great.
Is there an working script for AEM to deploy the roaming client to Mac machines?

**Comment by phantom1982** [comment]
Hi @jasper1986,

Unfortunately not. Our supported mass deployment for OSX would be using Apple Remote Desktop.  You can find the documentation for this here: https://support.umbrella.com/hc/en-us/articles/230905248-Umbrella-Roaming-Client-Mass-Deployment-Using-Apple-Remote-Desktop-in-OS-X

This may help you develop your own script, but it wouldn't be something we can support officially. AEM doesn't have their own scripting engine, so even for the Windows version we're simply using a Powershell script embedded in AEM to download and install the client.
